name: distributed-research-db

services:
  sqlserver-p1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: research_db_p1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Pass123
      - MSSQL_PID=Developer
    ports:
      - "14331:1433"
    volumes:
      - ./data/p1:/var/opt/mssql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - research-network

  sqlserver-p2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: research_db_p2
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Pass123
      - MSSQL_PID=Developer
    ports:
      - "14332:1433"
    volumes:
      - ./data/p2:/var/opt/mssql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - research-network

networks:
  research-network:
    driver: bridge
